### ISSUE TITLE
Blocknotify Support?

### ISSUE THREAD

**Issue by dlehenky** [aayanl/equihash-solomining#1]
Any chance we could get the znomp "blocknotify" support moved over? How about p2p?

**Comment by WaveringAna** [comment]
39b6979bec662da89a3119ff057850fb15e736c9, should work the same way as nomp

**Comment by dlehenky** [comment]
Thank you!!! I've not used p2p before. Any tips? I'm running zclassic v1.0.6. Also, is there a ZCL donation/contribution address?

**Comment by WaveringAna** [comment]
I think using both, blocknotify and p2p is a bit redundant because both will activate just 2-3 miliseconds from eachother. If you set it to true, p2p should run. A donation address is here `t3NPxHw1EnjNfqDf8Y2y9yutER6DGDV31ZY`

**Comment by dlehenky** [comment]
Yes, of course, one or the other. I have had "blocknotify" going before, just never tried p2p.
