### ISSUE TITLE
author Hello! I started it but the site didn't have that picture There is no valid shares after the start of the connection

### ISSUE THREAD

**Issue by wuhuaping** [aayanl/equihash-solomining#13]
There is no valid shares after the start of the connection
启动后连接 矿机没有出现有效的 shares
website
47.93.44.197:8080

 equihash-solomining@0.0.1 start /root/equihash-solomining
> LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/node_modules/stratum-pool/node_modules/equihashverify/build/Release/:$PWD/node_modules/equihashverify/build/Release/ node init.js

POSIX Connection Limit (Safe to ignore) POSIX module not installed and resource (connection) limit was not raised
CLI: CLI listening on port undefined
[Website][Thread 0][2017/05/08 19:21:13] Example app listening at http://0.0.0.0:8080
[Init][Thread 0][2017/05/08 19:21:13] Spawned proxy on 2 threads(s)
[PoolWorker][Thread 0][2017/05/08 19:21:13] p2p connection successful
[PoolWorker][Thread 0][2017/05/08 19:21:13] Stratum Pool Server Started for zclassic [ZCL] {equihash}
						Network Connected:	Mainnet
						Detected Reward Type:	POW
						Current Block Height:	104136
						Current Block Diff:	124953.136282143
						Current Connect Peers:	47
						Network Difficulty:	124012.5920610974
						Network Hash Rate:	5.70 MH
						Stratum Port(s):	9999
						Pool Fee Percent:	0%
						Block polling every:	100 ms
[PoolWorker][Thread 1][2017/05/08 19:21:13] Stratum Pool Server Started for zclassic [ZCL] {equihash}
[PoolWorker][Thread 1][2017/05/08 19:21:13] p2p connection successful
[PoolWorker][Thread 0][2017/05/08 19:21:15] Client IP detection failed, tcpProxyProtocol is enabled yet did not receive proxy protocol message, instead got data: {"id": 1, "method": "mining.subscribe", "params": ["equihashminer", null, "47.93.44.197", "9999"]}

[PoolWorker][Thread 0][2017/05/08 19:21:15] Authorized t1UCNcD1q57AzTjMvg7VfzrEJbf7mJ1YPQ5:x@::ffff:221.204.103.42
[PoolWorker][Thread 0][2017/05/08 19:22:08] No new blocks for 55 seconds - updating transactions & rebroadcasting work
[PoolWorker][Thread 0][2017/05/08 19:23:03] No new blocks for 55 seconds - updating

**Comment by wuhuaping** [comment]
47.93.44.197:8080

**Comment by Mordong** [comment]
всем похуй
