### ISSUE TITLE
Crash on return result._65.root in merkleTree.js

### ISSUE THREAD

**Issue by pbipbi** [aayanl/equihash-solomining#14]
/equihash-solomining/lib/stratum/merkleTree.js:
TypeError: Cannot read property 'root' of undefined

**Comment by TheComputerGenie** [comment]
change https://github.com/aayanl/equihash-solomining/blob/38cea0c0ca5aa8935afe7032a94f64e30ab21766/lib/stratum/merkleTree.js#L8
to
`return Object.values(result)[2].root;`

**Comment by VERTlG0** [comment]
this should be added to the docs
