### ISSUE TITLE
Mining Website doesnt show miner's stats only Global Network stats.

### ISSUE THREAD

**Issue by VERTlG0** [aayanl/equihash-solomining#17]
![equihash-solomining-websitestats](https://user-images.githubusercontent.com/3380510/36998945-9f5f2f18-208c-11e8-89d1-37105483db2e.png)

It only shows the global network stats but isnt showing my miner's stats. 

Heres output from my console: https://paste.pound-python.org/show/YUCLi0m8U9mUD1DcG8T4/

**Comment by TheComputerGenie** [comment]
You haven't found a block **to** show.
