### ISSUE TITLE
No database

### ISSUE THREAD

**Issue by WaveringAna** [aayanl/equihash-solomining#3]
Might leave it like this, will leave the issue up for suggestions

**Comment by dlehenky** [comment]
From my point of view, there's no need. No need for a front-end, either, for that matter. The console output is just fine - it's all I need to know. Even if those items are added, I hope you keep a "release" that's just the basics, as it is now, with "blocknotify" and/or p2p added. Just my 2 cents.

This project is an answer to a pray, and I thank you! I'll be making a ZCL donation (so you get ZenCash, too), so I'll be interested to see if "blocknotify"/p2p make it into the repo. Polling is simply a waste of time and energy.

**Comment by WaveringAna** [comment]
I figured just keeping a json file of the blocks found is enough 25934906e4510764792f0ad911b196e1dd8c3d4f
