### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by dlehenky** [aayanl/equihash-solomining#6]
Might we get proper timestamps on the log entries, i.e. not "Mar 03", but a standard, all numbers, date and time (local), e.g. 2017-03-24 09:47:36 ? It's hard to mine logs without timestamps :)

Also, can we at least have an option to log from only thread 0, rather than having every thread log the exact same entry? I have 12 threads running (with fork = "auto"), and it makes the log almost unreadable.

Finally, perhaps include the block # in the "Block notification" log entry?

I know this all may sound unimportant, but my status monitoring scripts rely on logging data to be useful.

Thank you!

**Comment by WaveringAna** [comment]
29b3b4fbace6ba39b7b83c7729840a41f0ce4b2d, timestamps are epoch times

**Comment by dlehenky** [comment]
Well, I was referring to the console logging, which I redirect to a file and then "tail -f" as needed. That hasn't changed. I believe (and I ain't no guru) what you changed is in the blocks.json "block found" logging, and I wouldn't think you wouldn't want to limit that to thread 0. Then again, I may be talking out my arse :)

**Comment by WaveringAna** [comment]
Ohhhhhh, I'll do that too

**Comment by dlehenky** [comment]
And the timestamp too, please??

**Comment by WaveringAna** [comment]
How does `Block 48769 found by rx470: 2017/03/25 00:05:15` look?

**Comment by dlehenky** [comment]
That's fine. Maybe date/time first?

**Comment by dlehenky** [comment]
I mentioned possibly adding the block # to the "block notify" log message, too. I feel like I'm pushing it, though :)

**Comment by WaveringAna** [comment]
36b8f34

**Comment by dlehenky** [comment]
On the console log, every log event is still be repeated verbatim for each thread, 12 in my case.
