### ISSUE TITLE
blocks.json: bad date value

### ISSUE THREAD

**Issue by dlehenky** [aayanl/equihash-solomining#7]
The "date": value given in blocks.json has 3 extra digits at the end, which prevents the correct date being printed by the linux "date +%s" command. If I remove the last the digits, the correct block time is displayed.

**Comment by WaveringAna** [comment]
It seems run fine on my end, can you give a sample epoch time with the extra 3 digits?

**Comment by dlehenky** [comment]
Here:

[{"block":79228,"finder":"node15","date":1490402101878},
{"block":79237,"finder":"node06","date":1490402670187}]


This is what “date” gave:

date --date='@1490402670187’
Thu Dec 24 14:43:07 MST 49198

This is without the last 3 digits:

date --date='@1490402670’
Fri Mar 24 18:44:30 MDT 2017


-David

**Comment by WaveringAna** [comment]
I'm not sure what could cause that execpt something being wrong with your node installation or the server's time is way off. Date() gets its time straight from what the OS tells it

```
api('block', {
     block: data.height,
     finder: data.worker,
     date: new Date().getTime()
});

**Comment by dlehenky** [comment]
Is that call returning milliseconds, too?

**Comment by WaveringAna** [comment]
I found the issue, the epoch time is done by local timezones and not UTC, hence why its 40000 years into the future

**Comment by WaveringAna** [comment]
with your date command, can you try `env TZ=EDT date` or whatever your timezone is?

**Comment by dlehenky** [comment]
Sure, hold on ... well, the simple "date" command returns: "Sun Mar 26 22:13:03 MDT 2017", after setting TZ. Using "date" on your json timestamp continues to return a date far in the future. Are you sure it's not returning milliseconds, too? It's curious that there are 3 extra decimal digits on the end of what is otherwise the correct epoch timestamp for the date.

**Comment by dlehenky** [comment]
Here's a printed timestamp from Optiminer's log: [2017-03-25 14:15:28.230]

Note the milliseconds on the end. Just thinking out loud.

**Comment by WaveringAna** [comment]
yeah you're right, javascript returns miliseconds, not seconds, I think `date -d (value/1000)` may work

**Comment by dlehenky** [comment]
Should do.
