### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by dlehenky** [aayanl/equihash-solomining#8]
I think you need some of the setup verbiage from Z-NOMP that covers "blocknotify" and a bit about p2p. It's really not that clear how to get it going, if that info isn't available. Maybe just link it?

Also, and I never found this "hint" anywhere, if you turn on "blocknotify" or "p2p" you should remember to set "blockRefreshInterval": to 0, otherwise the proxy will continue to poll the daemon. It would be nice if the code simply ignored "blockRefreshInterval": if either "blockNotify" or "p2p" are "true".

**Comment by WaveringAna** [comment]
af97395
